# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source ~/.git-completion.bash
source ~/.git-prompt.sh


export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export PS1='\u@\h \w$(__git_ps1 " [%s]") \$ '

source ~/.aliases
source ~/.functions

export NO_PROXY=$NO_PROXY,s3.amazonaws.com,ec2.amazonaws.com
export no_proxy=$NO_PROXY,s3.amazonaws.com,ec2.amazonaws.com

export AWS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
