# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

source ~/.git-completion.bash
source ~/.git-prompt.sh


# export PS1='[\u@\h \w$(__git_ps1 " (%s)")] \$ '
export GIT_PS1_SHOWCOLORHINTS=1
export GIT_PS1_SHOWDIRTYSTATE=1
export PROMPT_COMMAND='__git_ps1 "\u@\h:\w" " \\\$ "'

source ~/.aliases
